### ISSUE TITLE
ModuleNotFoundError: No module named 'selene_api'

### ISSUE THREAD

**Issue by j1nx** [OpenVoiceOS/ovos-personal-backend-ui#3] opened 2022-10-10 15:25 UTC
Because of the selene_api rename, this package needs updating

```
Traceback (most recent call last):
  File "/usr/bin/ovos-backend-manager", line 33, in <module>
    sys.exit(load_entry_point('ovos-backend-manager==0.0.1a1', 'console_scripts', 'ovos-backend-manager')())
  File "/usr/bin/ovos-backend-manager", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 849, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/ovos_backend_manager/__main__.py", line 1, in <module>
    from ovos_backend_manager.app import main
  File "/usr/lib/python3.10/site-packages/ovos_backend_manager/app.py", line 9, in <module>
    from ovos_backend_manager.menu import start
  File "/usr/lib/python3.10/site-packages/ovos_backend_manager/menu.py", line 5, in <module>
    from ovos_backend_manager.backend import backend_menu
  File "/usr/lib/python3.10/site-packages/ovos_backend_manager/backend.py", line 5, in <module>
    from ovos_local_backend.utils.geolocate import get_location_config
  File "/usr/lib/python3.10/site-packages/ovos_local_backend/utils/__init__.py", line 22, in <module>
    from ovos_local_backend.utils.geolocate import get_timezone, Geocoder
  File "/usr/lib/python3.10/site-packages/ovos_local_backend/utils/geolocate.py", line 9, in <module>
    from selene_api.api import GeolocationApi
ModuleNotFoundError: No module named 'selene_api'
```

**Comment by JarbasAl** [comment] 2022-10-10 16:21
this is a duplicate of https://github.com/OpenVoiceOS/ovos-personal-backend/issues/38

bump personal backend dependency and it will be fixed

**Closed as completed by JarbasAl** 2022-10-10 16:21 UTC
